use heck::ToLowerCamelCase;
use specta::{
    ResolvedTypes, Types,
    datatype::{DataType, Field, Function, Reference, Struct},
};
use specta_typescript::{Error, Exporter, FrameworkExporter, Typescript, define};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::path::Path;

const FRAMEWORK_HEADER: &str =
    "// This file has been generated by TauRPC. Do not edit this file manually.";

static PACKAGE_JSON: &str = r#"
{
    "name": ".taurpc",
    "types": "index.ts"
}
"#;

static BOILERPLATE_TS_IMPORT: &str = r#"
import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
"#;

static BOILERPLATE_TS_EXPORT: &str = r#"
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
"#;

/// Export the generated TS types with the code necessary for generating the client proxy.
///
/// By default, if the `export_to` attribute was not specified on the procedures macro, there will
/// be nothing exported. Otherwise the code will just be export to the .ts file specified by the user.
pub(super) fn export_types(
    export_path: &'static str,
    args_map: BTreeMap<String, String>,
    ts: Typescript,
    functions: BTreeMap<String, Vec<Function>>,
    types: Types,
) -> Result<(), Error> {
    // TODO: Maybe default to `true` once this is more stable.
    // Maybe use a runtime configuration system?
    let specta_phases_enabled = cfg!(not(feature = "specta_phases"));

    let mut types = if specta_phases_enabled {
        specta_serde::apply(types)
    } else {
        specta_serde::apply_phases(types)
    }
    .map_err(|err| Error::framework("Specta Serde validation failed", err))?;
    types.iter_mut(|ndt| rewrite_bigints_in_datatype(ndt.ty_mut()));

    Exporter::from(ts)
        .framework_prelude(FRAMEWORK_HEADER)
        .framework_runtime(move |mut exporter| {
            let mut out = String::new();

            out.push_str(&exporter.render_types()?);
            out.push_str(BOILERPLATE_TS_IMPORT);

            out.push_str(r#"const ARGS_MAP = "#);
            out.push_str(
                &serde_json::to_string_pretty(&args_map)
                    .map_err(|err| Error::framework("error stringify argument map", err))?,
            );
            out.push_str(";\n\n");

            out.push_str(
                &generate_functions_router(&functions, &exporter)
                    .map_err(|err| Error::framework("failed to generate router type", err))?,
            );
            out.push_str(BOILERPLATE_TS_EXPORT);

            Ok(out.into())
        })
        .export_to(export_path, &types)?;

    if export_path.ends_with("node_modules\\.taurpc\\index.ts") {
        let package_json_path = Path::new(export_path)
            .parent()
            .ok_or(Error::framework("", "Failed to create 'package.json' path"))?
            .join("package.json");

        std::fs::write(package_json_path, PACKAGE_JSON)
            .map_err(|err| Error::framework("Failed to create 'package.json' file", err))?
    }

    Ok(())
}

fn generate_functions_router(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
) -> Result<String, Error> {
    let mut router = Struct::named();

    for (path, path_functions) in functions {
        let mut function_names_and_funcs: Vec<_> =
            path_functions.iter().map(|f| (f.name(), f)).collect();
        function_names_and_funcs.sort_by(|a, b| a.0.cmp(b.0));

        let mut path_router = Struct::named();
        for (_, function) in function_names_and_funcs {
            let (name, field) = generate_function_field(function, exporter)?;
            path_router = path_router.field(name, field);
        }

        router = router.field(path.clone(), Field::new(path_router.build()));
    }

    let router_type = exporter.inline(&router.build())?;
    Ok(format!("export type Router = {router_type};\n"))
}

fn generate_function_field(
    function: &Function,
    exporter: &FrameworkExporter,
) -> Result<(String, Field), Error> {
    let args = function
        .args()
        .iter()
        .map(|(name, typ)| {
            render_reference_dt(typ, exporter)
                .map(|ty| format!("{}: {ty}", name.to_lower_camel_case()))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");

    let return_ty = if let Some(result) = function.result() {
        if let Some((dt_ok, _dt_err)) = extract_std_result(result, exporter.types) {
            render_reference_dt(dt_ok, exporter)?
        } else {
            render_reference_dt(result, exporter)?
        }
    } else {
        "void".to_string()
    };

    let name = function.name().split_once("_taurpc_fn__").unwrap().1;
    Ok((
        name.to_string(),
        Field::new(define(format!("({args}) => Promise<{return_ty}>")).into()),
    ))
}

// Render a `DataType` as a reference (or fallback to inline).
// Also handles Tauri channel references.
fn render_reference_dt(dt: &DataType, exporter: &FrameworkExporter) -> Result<String, Error> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = r.get(exporter.types.as_types())
        && ndt.name() == "TAURI_CHANNEL"
        && ndt.module_path().starts_with("tauri::")
    {
        let generic = if let Some((_, dt)) = r.generics().first() {
            match &dt {
                DataType::Reference(r) => exporter.reference(r)?,
                dt => exporter.inline(dt)?,
            }
            .into()
        } else {
            Cow::Borrowed("never")
        };
        Ok(format!("(response: {generic}) => void"))
    } else {
        match &dt {
            DataType::Reference(r) => exporter.reference(r),
            dt => exporter.inline(dt),
        }
    }
}

fn extract_std_result<'a>(
    dt: &'a DataType,
    types: &'a ResolvedTypes,
) -> Option<(&'a DataType, &'a DataType)> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = r.get(types.as_types())
        && ndt.name() == "Result"
        && (ndt.module_path() == "std::result" || ndt.module_path() == "core::result")
        && let [(_, ok), (_, err), ..] = r.generics()
    {
        return Some((ok, err));
    }

    None
}

/// This rewrites any large number types to a smaller type.
/// The newest version of Specta's Typescript exporter will always error on these (and `BigIntExportBehaviour` has been removed).
/// The recommendations for handling this now are documented here: https://github.com/specta-rs/specta/blob/d578bc055b7c5e6573d1cd723e7be56d33c28e5c/specta-typescript/src/error.rs#L11
///
// TODO: I (@oscartbeaumont) am going to do a follow up PR to support BigInt's properly in the future but this requires upstream work in Tauri so it's not possible at the moment.
fn rewrite_bigints_in_datatype(dt: &mut DataType) {
    use specta::datatype::{DataType, Fields, Primitive};

    fn rewrite_bigints_in_fields(fields: &mut Fields) {
        match fields {
            Fields::Unit => {}
            Fields::Unnamed(fields) => {
                for field in fields.fields_mut() {
                    if let Some(ty) = field.ty_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
            Fields::Named(fields) => {
                for (_, field) in fields.fields_mut() {
                    if let Some(ty) = field.ty_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
        }
    }

    match dt {
        DataType::Primitive(primitive) => match primitive {
            Primitive::usize | Primitive::u64 | Primitive::u128 => {
                *dt = DataType::Primitive(Primitive::u32);
            }
            Primitive::isize | Primitive::i64 | Primitive::i128 => {
                *dt = DataType::Primitive(Primitive::i32);
            }
            Primitive::f128 => {
                *dt = DataType::Primitive(Primitive::f64);
            }
            _ => {}
        },
        DataType::List(list) => rewrite_bigints_in_datatype(list.ty_mut()),
        DataType::Map(map) => {
            rewrite_bigints_in_datatype(map.key_ty_mut());
            rewrite_bigints_in_datatype(map.value_ty_mut());
        }
        DataType::Struct(strct) => rewrite_bigints_in_fields(strct.fields_mut()),
        DataType::Enum(enm) => {
            for (_, variant) in enm.variants_mut() {
                rewrite_bigints_in_fields(variant.fields_mut());
            }
        }
        DataType::Tuple(tuple) => {
            for item in tuple.elements_mut() {
                rewrite_bigints_in_datatype(item);
            }
        }
        DataType::Nullable(inner) => rewrite_bigints_in_datatype(inner),
        DataType::Reference(Reference::Named(reference)) => {
            for (_, generic) in reference.generics_mut() {
                rewrite_bigints_in_datatype(generic);
            }
        }
        DataType::Reference(Reference::Generic(_)) | DataType::Reference(Reference::Opaque(_)) => {}
    }
}
